### PR TITLE
call hasOwnProperty() on nodes to ignore properties or functions defined on Object

### PR DESCRIPTION
**Pull request by rick-kilgore**
call hasOwnProperty() on nodes to ignore properties or functions defined on Object
added task to Gruntfile.coffee to run the unit tests
updated the unit testing task to use grunt-jasmine-node - need to wait for the following PR to be merged before merging this one, though:
    https://github.com/jasmine-contrib/grunt-jasmine-node/pull/28

### CODE REVIEW

**Comment by chenglou** [comment]
Hey thanks! But why would there be anything on the prototype of the object? It's always kept internally.

**Comment by rick-kilgore** [comment]
Hi Cheng,

Sometimes people define helper functions on Object.prototype that can then be invoked on any Object.  The book "Javascript: the Good Parts" (or something like that) has several examples.  Apparently someone did something like that here, and when I tried to call wordsWithPrefix(), it got caught in an infinite loop.  It's pretty much always a good idea to check hasOwnProperty() when iterating over fields in an object.  Unless maybe if you're doing some kind of reflection on the data and you want to include fields or functions that are defined in base classes.

Thanks for the data structures by the way – love your module.  Saved me a lot of time! :)
- Rick

**Comment by chenglou** [comment]
Oh man… who still defines methods on Object prototype? That practice's been killed long ago for this very reason. I left the `own` keyword out because that's one less functional in a hot path, and because I had this luxury since the `nodes` are always clean internally.

But if that prevents infinite loops, I'll merge it soon.

**Comment by rick-kilgore** [comment]
Thanks man.  Yes, I agree, it shouldn't happen, but I still use own defensively.
- Rick

**Comment by chenglou** [comment]
@rick-kilgore omg sorry! There wasn't any notification, I thought you didn't submit the patch...
Thanks a lot for the work. The jasmine task breaks a test on `map`, I suspect it's because of how they set up some objects. I'll merge in your changes and go down the `exec` route instead.

Once again, sorry for the late notice!

**Pull request merged**
