### PR TITLE
pass node id to the callback in forEachNode

### PR DESCRIPTION
**Pull request by timsavery**
This is helpful when converted node structures into other downstream structures in my case. I am doing this conversion currently to employ Dijkstra's algorithm for shortest path. Reading the other issues thread, I thought maybe some simple changes would potentially help adoption. Also bumped version to 1.4.2 to indicate non-breaking change.

### CODE REVIEW

**Comment by chenglou** [comment]
Thanks!
Sure, I'll merge it tonight. Too bad the equivalent doesn't work for traversing edge.

**Comment by timsavery** [comment]
Thank you! Comment updated to indicate the second parameter is optional to be provided in the callback `...fn(nodeObject, [nodeId])...` since existing implementations do not need to change.

Let me know if you see anything else. Thanks again!

**Comment by chenglou** [comment]
Np, glad ot see the library's being used =).
The comment doesn't seem right though. You're passing `nodeId` all the time, so it should be just fn(nodeObject, nodeId). Whether you take it from the callback method side isn't any of the caller's business.
Also, can you add a test here? https://github.com/chenglou/data-structures/blob/master/tests/Graph.spec.coffee#L303

**Comment by timsavery** [comment]
You are right! I modified the comment and added a simple test iteration to validate the callback args. Let me know if you find anything else.

**Comment by chenglou** [comment]
It's good! Merged, updated bower package too, documented in wiki and history.md. Published to npm and bower. Thanks again =).

**Pull request merged**
